# Generated by Django 5.1.4 on 2025-01-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
